import { StyleSheet } from "react-native";
import { colors } from "../../config";
import commonStyle from "../../styles/common.style";

export default StyleSheet.create({
    container:{
        width:'100%',
        height:'100%',
        backgroundColor:colors.greyBackground
    },
    img:{
      width:136.71,
      height:142.42,
      alignSelf:'center'  
    },
    hello:{
        width:'90%',
        ...commonStyle.BoldFont,
        color:colors.black,
        fontSize:16,
        marginTop:'15%',
        textAlign:'left',
        alignSelf:'center'
    },
    hello1:{
        marginVertical:'5%',
        width:'90%',
        ...commonStyle.RegularFont,
        color:colors.black,
        fontSize:16,
        marginTop:'10%',
        textAlign:'right',
        alignSelf:'center'
    },
    address:{
        ...commonStyle.BoldFont,
        color:colors.black,
        fontSize:14,
        // textAlign:'center',
        // marginTop:Platform.OS=='ios'?'12%':'8%',
        width:'90%',
        alignSelf:'center',
        color:colors.dimGray
        // height:60,
        
    },
    itemView:{
        width:'90%',
        height:45,
        backgroundColor:colors.white,
        flexDirection:'row',
        alignItems:'center',
        alignSelf:'center',
        justifyContent:'flex-start',
        borderRadius:20,
        paddingHorizontal:'5%',
        marginTop:'5%'
    },
    itemViewActive:{
        width:'90%',
        height:45,
        backgroundColor:colors.white,
        flexDirection:'row',
        alignItems:'center',
        alignSelf:'center',
        justifyContent:'flex-start',
        borderRadius:20,
        paddingHorizontal:'5%',
        marginTop:'5%',
        borderWidth:1,
        borderColor:colors.primary
    },
    btn:{
        backgroundColor:colors.primary,
        width:'90%',
        height:47,
        alignSelf:'center',
        marginHorizontal:'10%',
        borderRadius:24,
        alignItems:'center',
        justifyContent:'center',
        marginVertical:'15%'
    },
    loginBtn:{
        ...commonStyle.BoldFont,
        color:colors.white,
    },
    modalContainer:{
        backgroundColor:'rgba(0,0,0,0.7)',
        height:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    modalConetnt:{
        padding:'3%',

        borderRadius:20,
        backgroundColor:colors.white,
        width:'90%'
    },
    consultantView1:{
        alignSelf:'center',
        paddingHorizontal:'5%',
        backgroundColor:colors.white,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        width:'90%',
        marginTop:'5%'
    },
    palneView:{
        width:115,
        height:28,
        borderRadius:10,
        backgroundColor:colors.primary,
        alignItems:'center',
        justifyContent:'center'
    },
    palneView1:{
        width:115,
        height:28,
        borderRadius:10,
        backgroundColor:colors.white,
        alignItems:'center',
        justifyContent:'center',
        borderWidth:1,
        borderColor:colors.primary
    },
    monthText1:{
        ...commonStyle.RegularItalicFont,
        color:colors.white,
        fontSize:11,
        textAlign:'center'
    },
    monthText2:{
        ...commonStyle.RegularItalicFont,
        color:colors.primary,
        fontSize:11,
        textAlign:'center'
    },
})