export default{
    onBoarding: require('./onBoarding.png'),
    signin: require('./signin.png'),
    forgot_password: require('./forgot_password.png'),
    signup:require('./signup.png'),
    add_photo: require('./add_photo.png'),
    section: require('./section.png'),
    menuBar: require('./menuBar.png'),
    avatar: require('./avatar.png'),
    back_home: require('./back_home.png'),
    menuBar1: require('./menuBar1.png'),
    dashes: require('./dashes.png'),
    choose_school: require('./choose_school.png'),
    car_img:require('./car_img.png'),
    car_img_new:require('./car_img_new.png'),
    awesome_school:require('./awesome_school.png'),
    mahada_school:require('./mahada_school.png'),
    sanena_school:require('./sanena_school.png'),
    avatar_new:require('./avatar_new.png'),
    my_avatar:require('./my_avatar.png'),
    my_avatar_placeholder:require('./my_avatar_placeholder.png'),
    empty_home:require('./empty_home.png'),
    female_active:require('./female_active.png'),
    male_active:require('./male_active.png'),
    section_active:require('./section_active.png'),
}