import { StyleSheet } from 'react-native';
import { colors } from '../../config';
import commonStyle from '../../styles/common.style';

export default StyleSheet.create({
    cont:{
        width:'100%',
        height:'100%',
        marginTop:'10%'
    },
    container:{
        borderRadius:20,
        backgroundColor:colors.white,
        width:'90%',
        alignSelf:'center',
        // paddingVertical:'5%'
    },
    content:{
        alignItems:'center',
        justifyContent:'center',
        width:'100%',
        height:'100%',
    },
    sideHeader:{
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:'5%',
        borderBottomColor:colors.dimGray,
        borderBottomWidth:1,
        height:60
    },
    sideHeader1:{
        // flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:'5%',
        height:60
    },
    sideHeader2:{
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:'5%',
        height:60
    },
    dateView:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignSelf:'center',
        alignItems:'center',
        width:'90%',
        height:80
    },
    dateView1:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignSelf:'center',
        alignItems:'center',
        width:'100%',
        height:40,
        borderWidth:1,
        borderColor:colors.primary
    },
    dateView2:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignSelf:'center',
        alignItems:'center',
        width:'100%',
        height:35
    },
    address:{
        ...commonStyle.BoldFont,
        fontSize:17,
        color:colors.blackOpacity,
        margin:'5%',
        textAlign:'center',
        marginTop:'15%'
    },
    address1:{
        ...commonStyle.BoldFont,
        fontSize:13,
        color:colors.black,
        marginHorizontal:'5%'
    },
    address2:{
        ...commonStyle.BoldFont,
        fontSize:17,
        color:colors.primary,
        marginHorizontal:'5%'
    },
    address3:{
        ...commonStyle.BoldFont,
        fontSize:13,
        color:colors.dimGray,
        marginHorizontal:'5%',
        textAlign:'left'
    },
    address4:{
        ...commonStyle.BoldFont,
        fontSize:17,
        color:colors.primary,
        marginHorizontal:'5%',
        marginTop:'3%',
        textAlign:'left'
    },
    date:{
        ...commonStyle.RegularFont,
        fontSize:14,
        color:colors.black
    },
    seperator:{
        height:1,
        backgroundColor: colors.primary
    },
    btn:{
        backgroundColor:colors.primary,
        width:309,
        height:47,
        alignSelf:'center',
        marginHorizontal:'10%',
        borderRadius:24,
        alignItems:'center',
        justifyContent:'center',
        marginVertical:'15%'
    },
    loginBtn:{
        ...commonStyle.BoldFont,
        color:colors.white,
    },
    modalContainer:{
        backgroundColor:'rgba(0,0,0,0.7)',
        height:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    modalConetnt1:{
        // padding:'3%',
        borderRadius:20,
        backgroundColor:colors.white,
        width:'90%',
        alignItems:'center',
        justifyContent:'center'
    },
})